# Generated by Django 3.0.2 on 2020-01-12 01:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200111_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapointalcohol',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alcohol_data_points', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='datapointnicotine',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nicotine_data_points', to=settings.AUTH_USER_MODEL),
        ),
    ]
