# Generated by Django 3.0.2 on 2020-01-12 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200112_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapointalcohol',
            name='category',
            field=models.CharField(choices=[('beer', 'beer'), ('spirits', 'spirits'), ('wine', 'wine')], default='wine', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datapointnicotine',
            name='category',
            field=models.CharField(choices=[('cigarette', 'cigarette'), ('gum', 'gum'), ('patch', 'patch'), ('vape', 'vape')], default='cigarette', max_length=25),
            preserve_default=False,
        ),
    ]
