# Generated by Django 3.0.2 on 2020-01-12 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_discord_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.FloatField()),
                ('strength', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vape', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
